//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ItemVenda
    {
        public int seqPedVendaItem { get; set; }

        [Required, Display(Name = "NRO. PEDIDO")]
        public int seqPedVenda { get; set; }

        [Required, Display(Name = "QUANTIDADE")]
        public decimal quantidade { get; set; }

        [Required, Display(Name = "QTD. EMBALAGEM")]
        public int embalagem { get; set; }

        [Required, Display(Name = "VALOR ITEM"), DataType(DataType.Currency)]
        public decimal vlrItem { get; set; }

        public virtual PedidoVenda PedidoVenda { get; set; }
    }
}
